Prefix: "&7[&4Clan&7]"

Message:
  hitAlly: '&2&lAlly hit'
  interactionNotAllowed: '&7&lNot Allowed'
  
  relationChanged: '&7Now %relative% is your %relation%'
  
  expGain: '&2+%exp%'
  expTooLow: '&4You don''t have enough clan experience'
  
  clanCreate: '&4You have created a new clan'
  clanDisband: '&4You have disbanded your clan'
  claimEnterTitle: '&7Chunk claimed'
  claimEnterSubtitle: '&7Claimer: %clan%'
  claimChunk: '&7You have claimed this chunk'
  
  unclaimChunk: '&7You have unclaimed this chunk'
  unclaimAll: '&7You have unclaimed all your chunks'
  
  rankChange: '&7Your rank has been changed to %rank%'  
    
Ranks:
  owner:
    color: aqua
    name: "owner"
  moderator:
    color: dark_aqua
    name: "moderator"
  trusted:
    color: green
    name: "trusted"
  member:
    color: gray
    name: "member"
  
Relations:
  allied:
    color: green
    name: "ally"
  enemy:
    color: red
    name: "enemy"
  neutral:
    color: white
    name: "neutral"

Commands:
  Name: #This will change the command name (Or alias).
    create: 'create'
    delete: 'delete'
    quit: 'quit'
    kick: 'kick'
    rank: 'rank'
    relation: 'relation'
    claim: 'claim'
    unclaim: 'unclaim'
  ClaimCosts: 
    #This will be costs of chunk claiming. 
    #The numbers refer to the next to be claimed. If a clan have 0 claims, the cost to refer is 1. 1 claim to refer 2 etc...
    #The last number will be the max chunk a clan can claim. Set all to 0 to remove the cost
    1: 10.0
    2: 40.0
    3: 100.0
    4: 400.0
    5: 1500.0
    6: 3500.0
    7: 10000.0
    8: 35000.0
    9: 85000.0
    10: 125000.0
  #NotSure
  #UnclaimExpReturn: 25 #This is a percentage. How much xp players will get back from unclaiming chunks
  UnclaimSubcommand:
    one: 'one'
    all: 'all'
  Message:
    commandWrong: '&4That command does not exist. &7Use /clan for help'
    commandOwnerOnly: '&4That command can be only executed by clan owners'
    commandModeratorOnly: '&4That command can be only executed by clan moderators'
    
    clanWrong: '&4A clan with that name does not exist'
    clanSame: '&4You can''t choose your same clan'
        
    playerWrongClan: '&4That player is not in your clan'
    playerInClan: '&7You are already in a clan'
    playerNotInClan: '&4You are not in a clan'
    otherPlayerNotInClan: '&4That player is not in a clan'
    playerInexistent: '&4A player with that name does not exist'
    
    createHelp: '&7/clan create &l*Name* *Tag*'
    createNameExist: '&4A clan with that name already exist'
    createClan: '&7You created a new clan!'
    
    deleteHelp: '&7/clan delete'
    deleteClan: '&7You have deleted your clan'
    deleteConfirm: '&7>> &4Click here to confirm &7<<' #This will show a clickable message
    
    quitHelp: '&7/clan quit'
    quitClan: '&7You have quit the clan'
    quitOwner: '&4Owner cannot quit the server'
    
    kickHelp: '&7/clan kick *player*'
    kickPlayer: '&7%player% has been kicked from the clan'
    
    rankHelp: '&7/clan rank *player* *rank* - Ranks: Moderator, Trusted or Member'
    rankChange: '%player%''s rank has been changed to %rank%'
    rankWrong: '&4That rank does not exist. &7Use Moderator, Trusted or Member'
    rankSame: '&4That player already have that rank'
    
    relationHelp: '&7/clan relation *clan* *relation* - Relations: ally, enemy or neutral'
    relationAlready: '&4That clan have already a relation with you. &7Set neutral to remove a relation'
    relationSame: '&4That clan already has the same relation'
    relationWrong: '&4That relation does not exist. &7Use Ally, enemy or neutral to remove a relation'
    
    claimHelp: '&7/clan claim'
    claimAlready: '&4This chunk is already claimed by %clan%'
    claimMaxReached: '&4You have reached the max number of claims'
    
    unclaimHelp: '&7/clan unclaim one<>all'
    unclaimEmpty: '&4This chunk is not claimed'
    unclaimOthers: '&4This chunk is not your'
    unclaimNoClaims: '&4Your clan does not have any claim'
    unclaimAllConfirm: '&7>> &4Click here to unclaim all chunks &7<<' #This will show a clickable message
    
Experience:
  enemyKill: 2.5 #When a clan member kill a member of an enemy clan
  potionBrew: 0.25 #When a potion is brewed in a clan claim
  
  silkTouch: false #Can the player have silk touch when mining the block?
  block: #When a clan member mine a block
    coal_ore: 0.15
    quartz_ore: 0.65
    glowing_redstone_ore: 0.75
    lapis_ore: 1.15
    emerald_ore: 15
    
  mob: #When a clan member kill a mob
    BAT: 0.1
    PIG: 0.2
    OCELOT: 0.25
    COW: 0.35
    MUSHROOM_COW: 1.25
    CHICKEN: 0.25
    HORSE: 0.4
    SKELETON_HORSE: 0.85
    ZOMBIE_HORSE: 2.25
    DONKEY: 0.55
    LLAMA: 0.55
    MULE: 0.55
    RABBIT: 0.25
    SHEEP: 0.4
    SQUID: 0.15
    WOLF: 0.35
    VILLAGER: 0.65
    POLAR_BEAR: 1.25
    SHULKER: 3.5
    SLIME: 0.015
    SNOWMAN: 0.15
    SPIDER: 0.25
    CAVE_SPIDER: 0.20
    SILVERFISH: 0.25
    SKELETON: 0.35
    STRAY: 0.40
    WITHER_SKELETON: 1.05
    ZOMBIE: 0.30
    HUSK: 0.35
    ZOMBIE_VILLAGER: 0.30
    CREEPER: 0.40
    VINDICATOR: 1.5
    EVOKER: 1.45
    VEX: 0.25
    WITCH: 0.95
    IRON_GOLEM: 1.85
    MAGMA_CUBE: 0.025
    PIG_ZOMBIE: 0.65
    GHAST: 2.5
    BLAZE: 0.75
    ELDER_GUARDIAN: 10
    GUARDIAN: 1.2
    GIANT: 25.0
    ENDERMAN: 1.15
    ENDERMITE: 0.15
    ENDER_DRAGON: 2000.0
    WITHER: 750.0